name: golang-library
files:
  - '*.*'
  - '.*'
  - '*'
  - '__tests__/*.go'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /pkgjson-description/g
    to: Leancloud sdk for golang.
  - from: /pkgjson/g
    to: ${PROJECT_NAME}
